# Generated by Django 4.1.6 on 2023-02-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activello', '0002_alter_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
